response1 = {u'Amount': [u'5.00'],
             u'AuthDesc': [u'Y'],
             u'Checksum': [u'2447380658'],
             u'Merchant_Id': [u'M_Wizcraft_12245'],
             u'Merchant_Param': [u''],
             u'Notes': [u'sdfasdasd'],
             u'Order_Id': [u'213123'],
             u'bank_name': [u''],
             u'billing_cust_address': [u'asdfasd'],
             u'billing_cust_city': [u'Hyderabad'],
             u'billing_cust_country': [u'India'],
             u'billing_cust_email': [u'lakshman@lakshmanprasad.com'],
             u'billing_cust_name': [u'Lakshman Prasad'],
             u'billing_cust_state': [u'Karnataka'],
             u'billing_cust_tel': [u'23423'],
             u'billing_zip_code': [u'5675432'],
             u'card_category': [u'CREDITCARD'],
             u'delivery_cust_address': [u'N/A'],
             u'delivery_cust_city': [u'N/A'],
             u'delivery_cust_country': [u'N/A'],
             u'delivery_cust_name': [u'N/A'],
             u'delivery_cust_state': [u'N/A'],
             u'delivery_cust_tel': [u'N/A'],
             u'delivery_zip_code': [u'N/A'],
             u'nb_bid': [u'233959'],
             u'nb_order_no': [u'CCA101038109'],
             u'return_url': [u'http://smackaho.st/payment-done/']}


response2 = {u'Amount': [u'5.00'],
             u'AuthDesc': [u'N'],
             u'Checksum': [u'2845511946'],
             u'Merchant_Id': [u'M_Wizcraft_12245'],
             u'Merchant_Param': [u''],
             u'Notes': [u'asdfasdsa'],
             u'Order_Id': [u'12312213'],
             u'bank_name': [u''],
             u'billing_cust_address': [u'asdasd'],
             u'billing_cust_city': [u'aasdas'],
             u'billing_cust_country': [u'India'],
             u'billing_cust_email': [u'afsdsafad@sdfgf.ff'],
             u'billing_cust_name': [u'asdasd asdasd'],
             u'billing_cust_state': [u'asdas'],
             u'billing_cust_tel': [u'23423'],
             u'billing_zip_code': [u'321213'],
             u'card_category': [u'CREDITCARD'],
             u'delivery_cust_address': [u'N/A'],
             u'delivery_cust_city': [u'N/A'],
             u'delivery_cust_country': [u'N/A'],
             u'delivery_cust_name': [u'N/A'],
             u'delivery_cust_state': [u'N/A'],
             u'delivery_cust_tel': [u'N/A'],
             u'delivery_zip_code': [u'N/A'],
             u'nb_bid': [u'234230'],
             u'nb_order_no': [u'CCA101038380'],
             u'return_url': [u'http://smackaho.st/payment-done/']}

response3 = {u'Amount': [u'5.00'],
             u'AuthDesc': [u'N'],
             u'Checksum': [u'1171395421'],
             u'Merchant_Id': [u'M_Wizcraft_12245'],
             u'Merchant_Param': [u''],
             u'Notes': [u'aasd'],
             u'Order_Id': [u'30992432:1286221675'],
             u'bank_name': [u''],
             u'billing_cust_address': [u'adasd'],
             u'billing_cust_city': [u'dfasd'],
             u'billing_cust_country': [u'India'],
             u'billing_cust_email': [u'dsafas@sfsdd.ddd'],
             u'billing_cust_name': [u'adasd'],
             u'billing_cust_state': [u'sdfasd'],
             u'billing_cust_tel': [u'23423'],
             u'billing_zip_code': [u'adas'],
             u'card_category': [u'CREDITCARD'],
             u'delivery_cust_address': [u'N/A'],
             u'delivery_cust_city': [u'N/A'],
             u'delivery_cust_country': [u'N/A'],
             u'delivery_cust_name': [u'N/A'],
             u'delivery_cust_state': [u'N/A'],
             u'delivery_cust_tel': [u'N/A'],
             u'delivery_zip_code': [u'N/A'],
             u'nb_bid': [u'234244'],
             u'nb_order_no': [u'CCA101038394'],
             u'return_url': [u'http://smackaho.st/payment-done/']}


from django.test import client

c = client.Client()
