response1 = {u'Amount': [u'5.00'],
             u'AuthDesc': [u'Y'],
             u'Checksum': [u'2447380658'],
             u'Merchant_Id': [u'M_Wizcraft_12245'],
             u'Merchant_Param': [u''],
             u'Notes': [u'sdfasdasd'],
             u'Order_Id': [u'213123'],
             u'bank_name': [u''],
             u'billing_cust_address': [u'asdfasd'],
             u'billing_cust_city': [u'Hyderabad'],
             u'billing_cust_country': [u'India'],
             u'billing_cust_email': [u'lakshman@lakshmanprasad.com'],
             u'billing_cust_name': [u'Lakshman Prasad'],
             u'billing_cust_state': [u'Karnataka'],
             u'billing_cust_tel': [u'23423'],
             u'billing_zip_code': [u'5675432'],
             u'card_category': [u'CREDITCARD'],
             u'delivery_cust_address': [u'N/A'],
             u'delivery_cust_city': [u'N/A'],
             u'delivery_cust_country': [u'N/A'],
             u'delivery_cust_name': [u'N/A'],
             u'delivery_cust_state': [u'N/A'],
             u'delivery_cust_tel': [u'N/A'],
             u'delivery_zip_code': [u'N/A'],
             u'nb_bid': [u'233959'],
             u'nb_order_no': [u'CCA101038109'],
             u'return_url': [u'http://smackaho.st/payment-done/']}


